# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ising')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ising')
    _ising = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ising', [dirname(__file__)])
        except ImportError:
            import _ising
            return _ising
        try:
            _mod = imp.load_module('_ising', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ising = swig_import_helper()
    del swig_import_helper
else:
    import _ising
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ising.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _ising.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ising.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ising.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ising.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ising.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ising.SwigPyIterator_copy(self)

    def next(self):
        return _ising.SwigPyIterator_next(self)

    def __next__(self):
        return _ising.SwigPyIterator___next__(self)

    def previous(self):
        return _ising.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ising.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ising.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ising.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ising.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ising.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ising.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ising.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _ising.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vector_double(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_double, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_double, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _ising.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ising.vector_double___nonzero__(self)

    def __bool__(self):
        return _ising.vector_double___bool__(self)

    def __len__(self):
        return _ising.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _ising.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ising.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ising.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ising.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ising.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ising.vector_double___setitem__(self, *args)

    def pop(self):
        return _ising.vector_double_pop(self)

    def append(self, x):
        return _ising.vector_double_append(self, x)

    def empty(self):
        return _ising.vector_double_empty(self)

    def size(self):
        return _ising.vector_double_size(self)

    def swap(self, v):
        return _ising.vector_double_swap(self, v)

    def begin(self):
        return _ising.vector_double_begin(self)

    def end(self):
        return _ising.vector_double_end(self)

    def rbegin(self):
        return _ising.vector_double_rbegin(self)

    def rend(self):
        return _ising.vector_double_rend(self)

    def clear(self):
        return _ising.vector_double_clear(self)

    def get_allocator(self):
        return _ising.vector_double_get_allocator(self)

    def pop_back(self):
        return _ising.vector_double_pop_back(self)

    def erase(self, *args):
        return _ising.vector_double_erase(self, *args)

    def __init__(self, *args):
        this = _ising.new_vector_double(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _ising.vector_double_push_back(self, x)

    def front(self):
        return _ising.vector_double_front(self)

    def back(self):
        return _ising.vector_double_back(self)

    def assign(self, n, x):
        return _ising.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _ising.vector_double_resize(self, *args)

    def insert(self, *args):
        return _ising.vector_double_insert(self, *args)

    def reserve(self, n):
        return _ising.vector_double_reserve(self, n)

    def capacity(self):
        return _ising.vector_double_capacity(self)
    __swig_destroy__ = _ising.delete_vector_double
    __del__ = lambda self: None
vector_double_swigregister = _ising.vector_double_swigregister
vector_double_swigregister(vector_double)

class Ising(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ising, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Ising, name)
    __repr__ = _swig_repr

    def __init__(self, iJ, iL, iT, iH):
        this = _ising.new_Ising(iJ, iL, iT, iH)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def reset_averages(self):
        return _ising.Ising_reset_averages(self)

    def compute_boltzmann_factors(self):
        return _ising.Ising_compute_boltzmann_factors(self)

    def metropolis_step(self):
        return _ising.Ising_metropolis_step(self)

    def one_monte_carlo_step_per_spin(self):
        return _ising.Ising_one_monte_carlo_step_per_spin(self)

    def magnetizationPerSpin(self):
        return _ising.Ising_magnetizationPerSpin(self)

    def energyPerSpin(self):
        return _ising.Ising_energyPerSpin(self)

    def run(self, MCSteps):
        return _ising.Ising_run(self, MCSteps)

    def set_H(self, iH):
        return _ising.Ising_set_H(self, iH)

    def set_T(self, iT):
        return _ising.Ising_set_T(self, iT)

    def get_mAvg(self):
        return _ising.Ising_get_mAvg(self)

    def get_m2Avg(self):
        return _ising.Ising_get_m2Avg(self)

    def get_eAvg(self):
        return _ising.Ising_get_eAvg(self)

    def get_e2Avg(self):
        return _ising.Ising_get_e2Avg(self)

    def get_T(self):
        return _ising.Ising_get_T(self)

    def get_H(self):
        return _ising.Ising_get_H(self)

    def get_s(self):
        return _ising.Ising_get_s(self)

    def get_mvals(self):
        return _ising.Ising_get_mvals(self)

    def get_evals(self):
        return _ising.Ising_get_evals(self)
    __swig_destroy__ = _ising.delete_Ising
    __del__ = lambda self: None
Ising_swigregister = _ising.Ising_swigregister
Ising_swigregister(Ising)

# This file is compatible with both classic and new-style classes.


